# Generated by Django 4.1.4 on 2022-12-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('res1', models.CharField(max_length=22)),
                ('res2', models.CharField(max_length=22)),
                ('date', models.DateField()),
            ],
        ),
    ]
